[lsp]
display-messages = true

[editor]  
scrolloff = 18
mouse = true
middle-click-paste = true
scroll-lines = 3
line-number = "relative" 
smart-case = true
auto-pairs = true
auto-completion = true
 
[keys.normal]
D = ["select_mode", "goto_line_end", "delete_selection"]
o = ["add_newline_below", "move_line_down"]
O = ["add_newline_above", "move_line_up"]
g = { "l" = "extend_to_line_end", "h" = "extend_to_line_start"}
g = { "g" = ["select_mode","goto_file_start"], "e" = ["select_mode","goto_last_line"]}
V = ["select_mode", "extend_line"]
