require("settings")
require("autocmds")
require("plugins/paq-nvim")
require("plugins/nvim-colorizer")
require("plugins/nvim-lspconfig")
require("plugins/indent-blankline-nvim")
require("plugins/telescope-fzf-native")
require("plugins/nvim-treesitter")
require("plugins/headlines-nvim")
require("plugins/nvim-autopairs")
require("plugins/neoscroll-nvim")
require("plugins/renamer-nvim")
require("plugins/mini-nvim")
require("plugins/nvim-tree")
require("plugins/telescope")
require("plugins/venn-nvim")
require("plugins/glow-nvim")
require("plugins/hop-nvim")
require("plugins/nvim-cmp")
require("plugins/firenvim")
require("plugins/null-ls")
require("compiler")
require("mappings")

-- Needs to be loaded in the end
require("plugins/tabout-nvim")
