
 

call plug#begin('~/.vim/plugged')

" Traces(Real time replace)
Plug 'markonm/traces.vim'

" easy motion
Plug 'easymotion/vim-easymotion'
Plug 'yuttie/comfortable-motion.vim'

" explorers
Plug 'junegunn/fzf.vim'
Plug 'jlanzarotta/bufexplorer'
 
" text 
Plug 'lervag/vimtex'

" Programming
Plug 'vim-scripts/LargeFile'
Plug 'tpope/vim-surround'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" colorscheme 
Plug 'rafalbromirski/vim-aurora' "dark
Plug 'tomasr/molokai' "dark
Plug 'yuttie/hydrangea-vim' "dark
Plug 'ghifarit53/tokyonight-vim' "dark|darkbluish

" multiple|dark|light (Tomorr..)
Plug 'chriskempson/vim-tomorrow-theme'
Plug 'junegunn/seoul256.vim'

" eye-friendly
Plug 'tomasiser/vim-code-dark' "dark
Plug 'tyrannicaltoucan/vim-deep-space' "dark
Plug 'arcticicestudio/nord-vim' "dark
Plug 'sjl/badwolf' " dark
Plug 'AlessandroYorba/Despacio' "darkshades 
Plug 'w0ng/vim-hybrid' "dark

Plug 'morhetz/gruvbox' "light|dark
Plug 'nightsense/cosmic_latte' " dark|light
Plug 'nightsense/stellarized' " dark|light
Plug 'cocopon/iceberg.vim' "dark|light
Plug 'nightsense/snow' "dark|light
Plug 'NLKNguyen/papercolor-theme' "dark|light

" Watching
" 

call plug#end()			

 
 
set nocompatible
filetype plugin indent on
syntax on
"                       LEADER KEY 
let mapleader="," 

" ====================== Plugin-settings ==========================

"                         vim-plug
nnoremap <Leader><Leader>p :PlugInstall<CR>
nnoremap <Leader><Leader>c :PlugClean<CR>
nnoremap <Leader><Leader>u :PlugUpdate<CR>

"                       Colorschemes    
let g:gruvbox_contrast_light = 'medium'
let g:gruvbox_contrast_dark = 'medium'
 
let g:tokyonight_style = 'night' "night/storm
let g:tokyonight_enable_italic = 1
 
let g:deepspace_italics = 1

let g:hybrid_custom_term_colors = 1
let g:hybrid_reduced_contrast = 1 " Remove this line if using the default palette.
let g:molokai_original = 1

let g:despacio_Sunset = 1
let g:despacio_Twilight = 0
let g:despacio_Midnight = 0
let g:despacio_Pitch = 0
 
let g:badwolf_tabline = 0
let g:badwolf_darkgutter = 1
let g:badwolf_css_props_highlight = 1
 
let g:seoul256_background = 233 

"                          Easymotion
" Move to word
let g:EasyMotion_keys = 'asdghklqwertyuiopzxcvbnmfj'
map f <Plug>(easymotion-bd-w)

" Explorers
nnoremap <leader>f :Files<CR>
let g:fzf_layout = {'down':'40%' }

nnoremap <leader>e :BufExplorer<CR>
nnoremap <silent> <F11> :BufExplorer<CR>
nnoremap <silent> <s-F11> :ToggleBufExplorer<CR>
nnoremap <silent> <m-F11> :BufExplorerHorizontalSplit<CR>
nnoremap <silent> <c-F11> :BufExplorerVerticalSplit<CR>

"                      Programming

"                       coc.nvim
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

command! -nargs=0 Prettier :CocCommand prettier.formatFile "prettier

" ======================= Key-bindings ==========================
 
" Easy redo 
nnoremap U :redo<CR>
 
" Do not lose selection after indentation.
vnoremap <silent> < <gv
vnoremap <silent> > >gv
 
" move backwards to the end of the word 
nnoremap E ge
 
" history
inoremap <Space> <C-]><Space><c-g>u
inoremap <CR> <CR><c-g>u
 
nnoremap           ;           :
vnoremap           ;           :
 
" ============== 'm'- manipulate, make, move, & more... =================
 
" buffer next 
nnoremap <leader><Space> :bn<CR>
" buffer delete 
nnoremap md :bd<CR>
" Write changes
nnoremap mm :w<CR>
" split 
nnoremap ms :new <CR> 
" vsplit 
nnoremap mv :vnew <CR> 

" viewports 
nmap m <C-w>
noremap me m=
" expand shrink 
nnoremap <C-j> m-
inoremap <C-j> <Esc>m-a
nnoremap <C-k> m+
inoremap <C-k> <Esc>m+a
 
" FANCY LINE MOVING
" nnoremap <C-K> <CMD>m .-2<CR>
" nnoremap <C-J> <CMD>m .+1<CR>
" nnoremap <C-H> <<
" nnoremap <C-L> >>  
"  
" vnoremap <C-K> :m '<-2<CR>gv
" vnoremap <C-J> :m '>+1<CR>gv
" vnoremap <C-H> <gv
" vnoremap <C-L> >gv 
" 
" " These lines conflict with the default bindings 
" inoremap <C-H> <CMD>normal <<<CR>
" inoremap <C-L> <CMD>normal >><CR>
" inoremap <C-K> <CMD>m .-2<CR>
" inoremap <C-J> <CMD>m .+1<CR>

" Copying and Pasting 
" copy the entire file to the clipboard
noremap Y :w <bar> :!xsel -b < %<CR><CR>
" Copy pasting (Using gvim to use inbuilt clipboards)
noremap <leader>y "+y 
noremap <leader>p "+p
" Don't clear the clipboard on exiting vim 
autocmd VimLeave * call system("xsel -ib", getreg('+'))

" To toggle numbering
nmap <leader>i :exec &nu==&rnu? "se nu!" : "se rnu!"<CR>

" nohl
nnoremap <silent><expr> H (&hls && v:hlsearch ? ':nohls' : ':set hls')."\n"

"                            NAVIGATION KEYBINDINGS 

" tabs
nnoremap tn :tabnew<Space>
nnoremap tk :tabnext<CR>
nnoremap tj :tabprev<CR>
nnoremap th :tabfirst<CR>
nnoremap tl :tablast<CR>
 
"todo 
nnoremap td :e ~/.todo.txt<CR>
 
" line in line scroll 
nnoremap j gj
nnoremap k gk

" if nofiletype then set it to text
autocmd BufNewFile,BufRead * if &filetype ==# '' | setlocal filetype=text | endif
autocmd BufEnter * if expand('%') ==# '' | setfiletype text | endif
" stay in normal mode after inserting a new line
noremap o o <Esc>
autocmd FileType text,markdown,conf noremap <buffer> o o<Esc>
noremap O O <Esc>
autocmd FileType text,markdown,conf noremap <buffer> O O<Esc>
 
" Source vimrc
nnoremap <leader>s :source ~/.vimrc<CR>

" ============================ Switches/Misc =============================

" numbering
set nu 

" background
set background=light

" 256 colors
set termguicolors

" Cursors
set cursorline
set cursorcolumn 
" https://github.com/vim/vim/issues/8908

set notimeout ttimeout ttimeoutlen=40 
set mouse=a
set scrolloff=15

" highlight matching braces
set showmatch

" How many tenths of a second to blink when matching brackets
set mat=0

" Set recursive search
set path+=**

" Use tab completion everywhere 
set wildmenu

" wrapping of long lines into multiple lines
set wrap

" history
set history=1000

" on some systems the backspace does not work as expected.
" this fixes the problem
set backspace=indent,eol,start

" encoding
set encoding=UTF-8

set signcolumn=number

"                       INDENTATION

set autoindent
set showmode 
set smartindent
set shiftwidth=4
set tabstop=4
set smarttab
set expandtab

"                       SEARCHING

" Ignorecase when searching
set ignorecase

" incremental search - Vim starts searching when we start typing
set incsearch

" When searching try to be smart about cases
set smartcase

" Highlight search results
set hlsearch

"                       PERFORMANCE

" fix slow scrolling that occurs when using mouse and relative numbers
set lazyredraw

" ========================= Highlighting  ============================

" ================ Folds ============================

" ================ File management ==================

" Turn off swap files
set noswapfile
set nobackup
set nowb

" reload files changed outside vim
set autoread
" Triger `autoread` when files changes on disk
autocmd FocusGained,BufEnter,CursorHold,CursorHoldI * if mode() != 'c' | checktime | endif
" Notification after file change
autocmd FileChangedShellPost *
            \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None

" ============== template / compile / run ====================

nnoremap <leader>t :!cp ~/templates/template.%:e %<Enter> 

"shortcut to run current filetype
map mr :call CompileRunGcc()<CR>
func! CompileRunGcc()
    exec "w"
    if &filetype == 'c'
        exec "!clear && gcc % -o %<"
        exec "!clear && time ./%<"
    elseif &filetype == 'cpp'
        exec "!clear && g++ % -o %<"
        exec "!clear && time ./%<"
    elseif &filetype == 'rust'
        exec "!clear && cargo build --manifest-path=%:p:h:h/Cargo.toml"
        exec "!time cargo run --manifest-path=%:p:h:h/Cargo.toml"
         
    "elseif &filetype == 'rust'
    "    exec "!clear && rustc %:p --out-dir=%:p:h"
    "    exec "!time " .expand("%:p:r")
    " elseif expand('%:t') == 'main.rs'
    "     exec "!clear && cargo build --manifest-path=%:p:h:h/Cargo.toml"
    "     exec "!time cargo run --manifest-path=%:p:h:h/Cargo.toml"

    elseif &filetype == 'java'
        exec "!clear && javac %"
        exec "!clear && time java -cp %:p:h %:t:r"
    elseif &filetype == 'sh'
        exec "!clear && time bash %"
    elseif &filetype == 'python'
        exec "!clear && time python3 %"
    elseif &filetype == 'javascript'
        exec "!clear && time node %"
    elseif &filetype == 'html'
        exec "!chromium % &"
    elseif &filetype == 'tex'
        exec "!pdflatex --output-directory=%:p:h %"
    elseif &filetype == 'go'
        exec "!go build %<"
        exec "!clear && time go run %"
    elseif &filetype == 'text'
        exec "!clear && echo 'words : ' && wc -w % && echo 'lines : ' && wc -l % && echo 'size : ' && du -h %"
    elseif &filetype == 'markdown'
        exec "!clear && echo 'words : ' && wc -w % && echo 'lines : ' && wc -l % && echo 'size : ' && du -h %"
    endif
endfunc

" ============================================================

colorscheme 
